### ISSUE TITLE
GenericEventOptions internal namespace

### ISSUE THREAD

**Issue by ldwedari** [opentracing-contrib/csharp-netcore#72] opened 2020-09-29 08:59 UTC
The _GenericEventOptions_ class is in an internal namespace (OpenTracing.Contrib.NetCore.Internal). As the class is not internal it should be moved to a not internal namespace. Also a _ConfigureGenericEvent_ extension method should be provided.

**Comment by cwe1ss** [comment] 2020-12-12 08:02
`GenericEventOptions` no longer exists in v0.7.0+ as it mostly was a duplicate of `GenericDiagnosticOptions`. Please look at #58 or the release notes of v0.7.0 to see how to configure generic DiagnosticListeners now.

**Closed by cwe1ss** 2020-12-12 08:02 UTC
