### ISSUE TITLE
Using this makes a lot of log noise coming from Microsoft.* 

### ISSUE THREAD

**Issue by Afshin-Ofx** [opentracing-contrib/csharp-netcore#69] opened 2020-08-28 02:44 UTC
Hi, 
Thanks for the great tools.
When I am using this nuget package, even though I've setup my logging in appseting.json to set the level of Microsoft logging to Warning and above, I am still getting lots of Microsoft.* level logs in jaeger ui.

Please can you let me know how I can filter out those logs ?

```c#
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
```
![jaeger-ui-logh](https://user-images.githubusercontent.com/69827730/91514829-1990b180-e92b-11ea-851a-2d3262da24cb.PNG)

**Comment by cwe1ss** [comment] 2020-10-06 17:26
I'm closing this as a duplicate of #58. That issue also already explains a few ways that you can use right now to reduce the noise.

**Closed by cwe1ss** 2020-10-06 17:26 UTC
